spring:
  application:
    name: workout-service
  datasource:
    url: jdbc:mysql://localhost:3306/workout
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      instance:
        preferIpAddress: true
jwt:
  master:
    user: gymmsMasterUser
    secret: gymms